//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using XConfig;

public partial class Config : ConfigBase
{
	public static Config Inst;

	[BindConfigFileName("equip_other", false)]
	public EquipOtherTable equipOtherTable = new EquipOtherTable();
	[BindConfigFileName("equip_weapon", false)]
	public EquipWeaponTable equipWeaponTable = new EquipWeaponTable();
	[BindConfigFileName("item_type", false)]
	public ItemTypeTable itemTypeTable = new ItemTypeTable();
	[BindConfigFileName("items", false)]
	public ItemsTable itemsTable = new ItemsTable();
	[BindConfigFileName("master_equipment", true)]
	public MasterEquipmentTable masterEquipmentTable = new MasterEquipmentTable();
	[BindConfigFileName("master_level", false)]
	public MasterLevelTable masterLevelTable = new MasterLevelTable();
	[BindConfigFileName("text", false)]
	public TextTable textTable = new TextTable();
}
