//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

public partial class Config
{
	[BindConfigFileName("equip_other", false)]
	public EquipOtherTable equipOtherTable = new EquipOtherTable();
}
[BindConfigFileName("equip_other", false)]
public partial class EquipOtherTable : XTable<int, EquipOtherRow>
{
    public override void OnInit()
	{
		for (int i = 0; i < _rows.Count; i++)
			_rows[i].OnAfterInit();

        for (int i = 0; i < _rows.Count; i++)
            Config.Inst.masterEquipmentTable.AddRow(_rows[i]);

        OnAfterInit();
	}
}
[BindConfigFileName("equip_other", false)]
public partial class EquipOtherRow : MasterEquipmentRow
{
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		base.ReadFromBytes(buffer);
		rowIndex = buffer.ReadInt32();
	}
}
