//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("example01", false)]
public partial class Example01Table : XTable<int, Example01Row>
{
}
[BindConfigFileName("example01", false)]
public partial class Example01Row : XRow<int>
{
	public override int mainKey1 => Id;
	public int Id => _id; int _id;
	public bool BoolField => _boolField; bool _boolField;
	public bool BoolFieldDefault => _boolFieldDefault; bool _boolFieldDefault;
	public byte ByteField => _byteField; byte _byteField;
	public Color ColorField => _colorField; Color _colorField;
	public DateTime DateTimeField => _dateTimeField; DateTime _dateTimeField;
	public EnumExample01 EnumField => _enumField; EnumExample01 _enumField;
	public float FloatField => _floatField; float _floatField;
	public short ShortField => _shortField; short _shortField;
	public Vector2 Vector2Field => _vector2Field; Vector2 _vector2Field;
	public Vector3 Vector3Field => _vector3Field; Vector3 _vector3Field;
	public Vector4 Vector4Field => _vector4Field; Vector4 _vector4Field;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _id = (int)value;}
		else _id = 0;
		if (buffer.ReadByte() == 1) { BoolType.ReadFromBytes(buffer, out Boolean value); _boolField = (bool)value;}
		else _boolField = false;
		if (buffer.ReadByte() == 1) { BoolType.ReadFromBytes(buffer, out Boolean value); _boolFieldDefault = (bool)value;}
		else _boolFieldDefault = true;
		if (buffer.ReadByte() == 1) { ByteType.ReadFromBytes(buffer, out Byte value); _byteField = (byte)value;}
		else _byteField = 0;
		if (buffer.ReadByte() == 1) { ColorType.ReadFromBytes(buffer, out Color value); _colorField = (Color)value;}
		else _colorField = Color.clear;
		if (buffer.ReadByte() == 1) { DateTimeType.ReadFromBytes(buffer, out DateTime value); _dateTimeField = (DateTime)value;}
		else _dateTimeField = DateTime.MinValue;
		if (buffer.ReadByte() == 1) { EnumType.ReadFromBytes(buffer, out short value); _enumField = (EnumExample01)value;}
		else _enumField = EnumExample01.Value0;
		if (buffer.ReadByte() == 1) { FloatType.ReadFromBytes(buffer, out Single value); _floatField = (float)value;}
		else _floatField = 0f;
		if (buffer.ReadByte() == 1) { ShortType.ReadFromBytes(buffer, out Int16 value); _shortField = (short)value;}
		else _shortField = 0;
		if (buffer.ReadByte() == 1) { Vector2Type.ReadFromBytes(buffer, out Vector2 value); _vector2Field = (Vector2)value;}
		else _vector2Field = Vector2.zero;
		if (buffer.ReadByte() == 1) { Vector3Type.ReadFromBytes(buffer, out Vector3 value); _vector3Field = (Vector3)value;}
		else _vector3Field = Vector3.zero;
		if (buffer.ReadByte() == 1) { Vector4Type.ReadFromBytes(buffer, out Vector4 value); _vector4Field = (Vector4)value;}
		else _vector4Field = Vector4.zero;
	}
}
