//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

public partial class Config
{
	[BindConfigPath("item_type")]
	public ItemTypeTable itemTypeTable = new ItemTypeTable();
}
[Serializable]
public partial class ItemTypeTable : XTable
{
	public List<ItemTypeRow> rows { get { return _tableRows; }}
	List<ItemTypeRow> _tableRows;
	override public void FromBytes(BytesBuffer buffer)
	{
		if (_tableRows == null)
		{
			_tableRows = new List<ItemTypeRow>();
			ushort rowCount = buffer.ReadUInt16();
			for (int i = 0; i < rowCount; i++)
			{
				ItemTypeRow row = new ItemTypeRow();
				row.FromBytes(buffer);
				_tableRows.Add(row);
			}
		}
		else
		{
			ushort rowCount = buffer.ReadUInt16();
			for (int i = 0; i < rowCount; i++)
				_tableRows[i].FromBytes(buffer);
		}
	}
	Dictionary<int, ItemTypeRow> _intMajorKey2Row;
	override public void Init()
	{
		ItemTypeRow row = null;
		_intMajorKey2Row = new Dictionary<int, ItemTypeRow>();
		for (int i = 0; i < _tableRows.Count; i++)
		{
			row = _tableRows[i];
			int majorKey = row.Id;
			DebugUtil.Assert(!_intMajorKey2Row.ContainsKey(majorKey), "{0} 主键重复：{1}，请先按键盘【alt+r】导出配置试试！", name, majorKey);
			_intMajorKey2Row.Add(majorKey, row);
		}
	}
	virtual public ItemTypeRow GetValue(int majorKey, bool isAssert=true)
	{
		ItemTypeRow row;
		if (_intMajorKey2Row.TryGetValue(majorKey, out row))
			return row;
		if (isAssert)
			DebugUtil.Assert(row != null, "{0} 找不到指定主键为 {1} 的行，请先按键盘【alt+r】导出配置试试！", name, majorKey);
		return null;
	}
	virtual public bool TryGetValue(int majorKey, out ItemTypeRow row)
	{
		return _intMajorKey2Row.TryGetValue(majorKey, out row);
	}
	public bool ContainsKey(int majorKey)
	{
		return _intMajorKey2Row.ContainsKey(majorKey);
	}
	public void AddRow(ItemTypeRow row)
	{
		if (!_intMajorKey2Row.ContainsKey(row.Id))
		{
			_tableRows.Add(row);
			_intMajorKey2Row.Add(row.Id, row);
		}
	}
	override public void OnInit()
	{
		for (int i = 0; i < _tableRows.Count; i++)
			_tableRows[i].OnAfterInit();


		OnAfterInit();
	}
}
[Serializable]
public partial class ItemTypeRow : XRow
{
	[SerializeField]
	private int _Id;
	public int Id{ get { return _Id; }}
	[SerializeField]
	private string _IdName;
	public string IdName{ get { return _IdName; }}
	[SerializeField]
	private string _Name;
	public string Name{ get { return _Name; }}
	[SerializeField]
	private int _CreateType;
	public int CreateType{ get { return _CreateType; }}
	[SerializeField]
	private string _ClientExtArgs;
	public string ClientExtArgs{ get { return _ClientExtArgs; }}
	[SerializeField]
	private string _ServerExtArgs;
	public string ServerExtArgs{ get { return _ServerExtArgs; }}
	[SerializeField]
	private int _ProxyRemoveOrder;
	public int ProxyRemoveOrder{ get { return _ProxyRemoveOrder; }}
	[SerializeField]
	private bool _CanAdd;
	public bool CanAdd{ get { return _CanAdd; }}
	[SerializeField]
	private bool _CanRemove;
	public bool CanRemove{ get { return _CanRemove; }}
	[SerializeField]
	private bool _CanCheckCount;
	public bool CanCheckCount{ get { return _CanCheckCount; }}
	[SerializeField]
	private string _SmallIcon;
	public string SmallIcon{ get { return _SmallIcon; }}
	[SerializeField]
	private uint _WarehouseType;
	public uint WarehouseType{ get { return _WarehouseType; }}
	[SerializeField]
	private int _Order;
	public int Order{ get { return _Order; }}
	[SerializeField]
	private Vector2 _xy;
	public Vector2 xy{ get { return _xy; }}
	[SerializeField]
	private Vector3 _xy3;
	public Vector3 xy3{ get { return _xy3; }}
	[SerializeField]
	private float _f1;
	public float f1{ get { return _f1; }}
	[SerializeField]
	private Color _c1;
	public Color c1{ get { return _c1; }}
	[SerializeField]
	private DateTime _t1;
	public DateTime t1{ get { return _t1; }}
	[SerializeField]
	private FlagType _flag;
	public FlagType flag{ get { return _flag; }}
	override public void FromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) _Id = IntType.ReadFromBytes(buffer);
		else _Id = 0;
		if (buffer.ReadByte() == 1) _IdName = StringType.ReadFromBytes(buffer);
		else _IdName = string.Empty;
		if (buffer.ReadByte() == 1) _Name = StringType.ReadFromBytes(buffer);
		else _Name = string.Empty;
		if (buffer.ReadByte() == 1) _CreateType = IntType.ReadFromBytes(buffer);
		else _CreateType = 0;
		if (buffer.ReadByte() == 1) _ClientExtArgs = StringType.ReadFromBytes(buffer);
		else _ClientExtArgs = string.Empty;
		if (buffer.ReadByte() == 1) _ServerExtArgs = StringType.ReadFromBytes(buffer);
		else _ServerExtArgs = string.Empty;
		if (buffer.ReadByte() == 1) _ProxyRemoveOrder = IntType.ReadFromBytes(buffer);
		else _ProxyRemoveOrder = 999;
		if (buffer.ReadByte() == 1) _CanAdd = BoolType.ReadFromBytes(buffer);
		else _CanAdd = true;
		if (buffer.ReadByte() == 1) _CanRemove = BoolType.ReadFromBytes(buffer);
		else _CanRemove = true;
		if (buffer.ReadByte() == 1) _CanCheckCount = BoolType.ReadFromBytes(buffer);
		else _CanCheckCount = true;
		if (buffer.ReadByte() == 1) _SmallIcon = StringType.ReadFromBytes(buffer);
		else _SmallIcon = string.Empty;
		if (buffer.ReadByte() == 1) _WarehouseType = UIntType.ReadFromBytes(buffer);
		else _WarehouseType = 0;
		if (buffer.ReadByte() == 1) _Order = IntType.ReadFromBytes(buffer);
		else _Order = 0;
		if (buffer.ReadByte() == 1) _xy = Vector2Type.ReadFromBytes(buffer);
		else _xy = Vector2.zero;
		if (buffer.ReadByte() == 1) _xy3 = Vector3Type.ReadFromBytes(buffer);
		else _xy3 = Vector3.zero;
		if (buffer.ReadByte() == 1) _f1 = FloatType.ReadFromBytes(buffer);
		else _f1 = 0f;
		if (buffer.ReadByte() == 1) _c1 = ColorType.ReadFromBytes(buffer);
		else _c1 = Color.clear;
		if (buffer.ReadByte() == 1) _t1 = DateTimeType.ReadFromBytes(buffer);
		else _t1 = DateTime.MinValue;
		if (buffer.ReadByte() == 1) _flag = (FlagType)EnumType.ReadFromBytes(buffer);
		else _flag = FlagType.None;
		rowIndex = buffer.ReadInt32();
	}
}
