//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

public partial class Config
{
	[BindConfigPath("master_equipment")]
	public MasterEquipmentTable masterEquipmentTable = new MasterEquipmentTable();
}
[Serializable]
public partial class MasterEquipmentTable : XTable
{
	public List<MasterEquipmentRow> rows { get { return _tableRows; }}
	List<MasterEquipmentRow> _tableRows;
	override public void FromBytes(BytesBuffer buffer)
	{
		if (_tableRows == null)
		{
			_tableRows = new List<MasterEquipmentRow>();
			ushort rowCount = buffer.ReadUInt16();
			for (int i = 0; i < rowCount; i++)
			{
				MasterEquipmentRow row = new MasterEquipmentRow();
				row.FromBytes(buffer);
				_tableRows.Add(row);
			}
		}
		else
		{
			ushort rowCount = buffer.ReadUInt16();
			for (int i = 0; i < rowCount; i++)
				_tableRows[i].FromBytes(buffer);
		}
	}
	Dictionary<int, MasterEquipmentRow> _intMajorKey2Row;
	override public void Init()
	{
		MasterEquipmentRow row = null;
		_intMajorKey2Row = new Dictionary<int, MasterEquipmentRow>();
		for (int i = 0; i < _tableRows.Count; i++)
		{
			row = _tableRows[i];
			int majorKey = row.Id;
			DebugUtil.Assert(!_intMajorKey2Row.ContainsKey(majorKey), "{0} 主键重复：{1}，请先按键盘【alt+r】导出配置试试！", name, majorKey);
			_intMajorKey2Row.Add(majorKey, row);
		}
	}
	virtual public MasterEquipmentRow GetValue(int majorKey, bool isAssert=true)
	{
		MasterEquipmentRow row;
		if (_intMajorKey2Row.TryGetValue(majorKey, out row))
			return row;
		if (isAssert)
			DebugUtil.Assert(row != null, "{0} 找不到指定主键为 {1} 的行，请先按键盘【alt+r】导出配置试试！", name, majorKey);
		return null;
	}
	virtual public bool TryGetValue(int majorKey, out MasterEquipmentRow row)
	{
		return _intMajorKey2Row.TryGetValue(majorKey, out row);
	}
	public bool ContainsKey(int majorKey)
	{
		return _intMajorKey2Row.ContainsKey(majorKey);
	}
	public void AddRow(MasterEquipmentRow row)
	{
		if (!_intMajorKey2Row.ContainsKey(row.Id))
		{
			_tableRows.Add(row);
			_intMajorKey2Row.Add(row.Id, row);
		}
	}
	override public void OnInit()
	{
		for (int i = 0; i < _tableRows.Count; i++)
			_tableRows[i].OnAfterInit();


		OnAfterInit();
	}
}
[Serializable]
public partial class MasterEquipmentRow : XRow
{
	[SerializeField]
	private int _Id;
	public int Id{ get { return _Id; }}
	[SerializeField]
	private int _ValueLevel;
	public int ValueLevel{ get { return _ValueLevel; }}
	[SerializeField]
	private int _UseLevel;
	public int UseLevel{ get { return _UseLevel; }}
	[SerializeField]
	private int _StrengthenId;
	public int StrengthenId{ get { return _StrengthenId; }}
	[SerializeField]
	private int _InitStrengthenLevel;
	public int InitStrengthenLevel{ get { return _InitStrengthenLevel; }}
	[SerializeField]
	private int _StrengthenLevelMax;
	public int StrengthenLevelMax{ get { return _StrengthenLevelMax; }}
	[SerializeField]
	private int _JewelCount;
	public int JewelCount{ get { return _JewelCount; }}
	[SerializeField]
	private List<int> _JewelQuality;
	private ReadOnlyCollection<int> _jewelQualityReadOnlyCache;
	public ReadOnlyCollection<int> JewelQuality { get { return _jewelQualityReadOnlyCache ?? (_jewelQualityReadOnlyCache = _JewelQuality.AsReadOnly()); } }
	[SerializeField]
	private int _SellDropCount;
	public int SellDropCount{ get { return _SellDropCount; }}
	[SerializeField]
	[ConfigReference("UnlockItem")]
	private string _UnlockItemId;
	public string UnlockItemId{ get { return _UnlockItemId; }}
	private ItemsRow _unlockItem;
	public ItemsRow UnlockItem
	{
		get
		{
			if (string.IsNullOrEmpty(_UnlockItemId)) return null;
			return _unlockItem ?? (_unlockItem = Config.Inst.itemsTable.GetValue(int.Parse(UnlockItemId)));
		}
	}
	[SerializeField]
	private float _DurabilityCostRate;
	public float DurabilityCostRate{ get { return _DurabilityCostRate; }}
	override public void FromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) _Id = IntType.ReadFromBytes(buffer);
		else _Id = 0;
		if (buffer.ReadByte() == 1) _ValueLevel = IntType.ReadFromBytes(buffer);
		else _ValueLevel = 0;
		if (buffer.ReadByte() == 1) _UseLevel = IntType.ReadFromBytes(buffer);
		else _UseLevel = 0;
		if (buffer.ReadByte() == 1) _StrengthenId = IntType.ReadFromBytes(buffer);
		else _StrengthenId = 0;
		if (buffer.ReadByte() == 1) _InitStrengthenLevel = IntType.ReadFromBytes(buffer);
		else _InitStrengthenLevel = 0;
		if (buffer.ReadByte() == 1) _StrengthenLevelMax = IntType.ReadFromBytes(buffer);
		else _StrengthenLevelMax = 0;
		if (buffer.ReadByte() == 1) _JewelCount = IntType.ReadFromBytes(buffer);
		else _JewelCount = 0;
		_JewelQuality = new List<int>();
		if (buffer.ReadByte() == 1)
		{
			byte itemCount = buffer.ReadByte();
			for (int i = 0; i < itemCount; i++) _JewelQuality.Add(IntType.ReadFromBytes(buffer));
		}
		if (buffer.ReadByte() == 1) _SellDropCount = IntType.ReadFromBytes(buffer);
		else _SellDropCount = 1;
		_unlockItem = null;
		if (buffer.ReadByte() == 1) _UnlockItemId = ReferenceType.ReadFromBytes(buffer);
		else _UnlockItemId = null;
		if (buffer.ReadByte() == 1) _DurabilityCostRate = FloatType.ReadFromBytes(buffer);
		else _DurabilityCostRate = 0f;
		rowIndex = buffer.ReadInt32();
	}
}
