//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("base_ref_type", false)]
public partial class BaseRefTypeTable : XTable<int, BaseRefTypeRow>
{
}
[BindConfigFileName("base_ref_type", false)]
public partial class BaseRefTypeRow : XRow<int>
{
	public override int mainKey1 => Id;
	public int Id => _id; int _id;
	public string StringField => _stringField; string _stringField;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _id = (int)value;}
		else _id = 0;
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _stringField = (string)value;}
		else _stringField = string.Empty;
	}
}
