//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("child1", false)]
public partial class Child1Table : XTable<int, Child1Row>
{
}
[BindConfigFileName("child1", false)]
public partial class Child1Row : ParentRow
{
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		base.ReadFromBytes(buffer);
	}
}
