//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("child2", false)]
public partial class Child2Table : XTable<int, Child2Row>
{
}
[BindConfigFileName("child2", false)]
public partial class Child2Row : ParentRow
{
	public string Child2Value1 => _child2Value1; string _child2Value1;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		base.ReadFromBytes(buffer);
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _child2Value1 = (string)value;}
		else _child2Value1 = string.Empty;
	}
}
