//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using XConfig;

public partial class Config : ConfigBase
{
	public static Config Inst => _inst ?? (_inst = new Config());
	static Config _inst;

	[BindConfigFileName("base_ref_type", false)]
	public BaseRefTypeTable baseRefTypeTable = new BaseRefTypeTable();
	[BindConfigFileName("base_type", false)]
	public BaseTypeTable baseTypeTable = new BaseTypeTable();
	[BindConfigFileName("child1", false)]
	public Child1Table child1Table = new Child1Table();
	[BindConfigFileName("child2", false)]
	public Child2Table child2Table = new Child2Table();
	[BindConfigFileName("double_key", false)]
	public DoubleKeyTable doubleKeyTable = new DoubleKeyTable();
	[BindConfigFileName("parent", true)]
	public ParentTable parentTable = new ParentTable();
	[BindConfigFileName("partial_table", false)]
	public PartialTableTable partialTableTable = new PartialTableTable();
}
