//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("custom_config_type", false)]
public partial class CustomConfigTypeTable : XTable<int, CustomConfigTypeRow>
{
}
[BindConfigFileName("custom_config_type", false)]
public partial class CustomConfigTypeRow : XRow<int>
{
	public override int mainKey1 => Id;
	public int Id => _id; int _id;
	public ItemType Item => _item; ItemType _item;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _id = (int)value;}
		else _id = 0;
		if (buffer.ReadByte() == 1) { ItemType.ReadFromBytes(buffer, out ItemType value); _item = (ItemType)value;}
		else _item = null;
	}
}
