//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("double_key", false)]
public partial class DoubleKeyTable : XTable<int, int, DoubleKeyRow>
{
}
[BindConfigFileName("double_key", false)]
public partial class DoubleKeyRow : XRow<int, int>
{
	public override int mainKey1 => Key1;
	public override int mainKey2 => Key2;
	public int Key1 => _key1; int _key1;
	public int Key2 => _key2; int _key2;
	public int Value => _value; int _value;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _key1 = (int)value;}
		else _key1 = 0;
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _key2 = (int)value;}
		else _key2 = 0;
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _value = (int)value;}
		else _value = 0;
	}
}
