//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("hello_world", false)]
public partial class HelloWorldTable : XTable<int, HelloWorldRow>
{
}
[BindConfigFileName("hello_world", false)]
public partial class HelloWorldRow : XRow<int>
{
	public override int mainKey1 => Id;
	public int Id => _id; int _id;
	public string Name => _name; string _name;
	public string Field => _field; string _field;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _id = (int)value;}
		else _id = 0;
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _name = (string)value;}
		else _name = string.Empty;
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _field = (string)value;}
		else _field = string.Empty;
	}
}
