//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("parent", true)]
public partial class ParentTable : XTable<int, ParentRow>
{
	public override void Init()
	{
		base.Init();

		foreach (var row in Config.Inst.child1Table.rows)
			AddRow(row);

		foreach (var row in Config.Inst.child2Table.rows)
			AddRow(row);

	}
}
[BindConfigFileName("parent", true)]
public partial class ParentRow : XRow<int>
{
	public override int mainKey1 => Key;
	public int Key => _key; int _key;
	public string ParentValue1 => _parentValue1; string _parentValue1;
	public float ParentValue2 => _parentValue2; float _parentValue2;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _key = (int)value;}
		else _key = 0;
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _parentValue1 = (string)value;}
		else _parentValue1 = string.Empty;
		if (buffer.ReadByte() == 1) { FloatType.ReadFromBytes(buffer, out Single value); _parentValue2 = (float)value;}
		else _parentValue2 = 0f;
	}
}
