//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System;
using XConfig;

[BindConfigFileName("partial_table", false)]
public partial class PartialTableTable : XTable<int, PartialTableRow>
{
}
[BindConfigFileName("partial_table", false)]
public partial class PartialTableRow : XRow<int>
{
	public override int mainKey1 => Key1;
	public int Key1 => _key1; int _key1;
	public string Path => _path; string _path;
	public override void ReadFromBytes(BytesBuffer buffer)
	{
		if (buffer.ReadByte() == 1) { IntType.ReadFromBytes(buffer, out Int32 value); _key1 = (int)value;}
		else _key1 = 0;
		if (buffer.ReadByte() == 1) { StringType.ReadFromBytes(buffer, out String value); _path = (string)value;}
		else _path = string.Empty;
	}
}
