using System;
using System.Collections.Generic;
using System.Linq;

namespace XConfig.Editor
{
    public class ConfigCodeFileExporter : TextFileExporter
    {
        private const string CLASS_TEMPLATE =
            @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using XConfig;
";

        IEnumerable<ConfigFileImporter> importers;

        public ConfigCodeFileExporter(string outFilePath, ConfigFileContext context) : base(outFilePath)
        {
            this.importers = context.fileName2Importer.OrderBy(kvp => kvp.Key).Select(kvp => kvp.Value);
        }
        protected override void DoExport()
        {
            WriteLine(CLASS_TEMPLATE);//写类文件头
            WriteConfigCode();
        }
        void WriteConfigCode()
        {
            WriteLine("public partial class Config : ConfigBase");
            WriteLine("{");
            TabShift(1);
            WriteLine("public static Config Inst => _inst ?? (_inst = new Config());");
            WriteLine("static Config _inst;");
            EmptyLine();
            foreach (var importer in importers) 
            {
                string isParent = importer.isParent ? "true" : "false";
                WriteLine($"[BindConfigFileName(\"{importer.fileName}\", {isParent})]");
                WriteLine("public {0} {1};", importer.tableClassName, importer.lowerTableClassName);
            }
            EmptyLine();
            WriteInitFunction();
            TabShift(-1);
            WriteLine("}");
        }

        void WriteInitFunction()
        {
            WriteLine("public override void Init(bool isFromGenerateConfig = false)");
            WriteLine("{");
            TabShift(1);
            foreach (var importer in importers)
                WriteLine($"{importer.lowerTableClassName} = new {importer.tableClassName}();");
            EmptyLine();
            WriteLine("base.Init(isFromGenerateConfig);");
            TabShift(-1);
            WriteLine("}");
        }
    }
}